spring:
  datasource:
    username: root
    password: Passwd23!
    url: jdbc:mysql://localhost:3306/online_exam_platform?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    encoding:
      force: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    mode: HTML
    servlet:
      content-type: text/html
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.rong.pojo

